onboarding = false

[theme]
name = "gruvbox"
auto_switch = false

[ui]
agent_panel_sort = "spaces"
sidebar_width = 32
sidebar_min_width = 0
sidebar_max_width = 36
pane_gaps = false

[keys]
prefix = "`"
